baseURL = 'https://frlute.github.io/cs-cookbook/'
languageCode = 'en-us'
title = 'My New Hugo Site'
themesdir ='config/themes'
theme='ananke'
publishdir = 'public'
i18ndir = 'config/i18n'
staticdir = 'config/static'
resourcedir = 'config/resources'
layoutdir = 'config/layouts'
assetsdir = 'config/assets'